services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ./api/.env
    volumes:
      - ./api:/app
    restart: always
    networks:
      - travel_network

  streamlit:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    depends_on:
      - api
    volumes:
      - .:/app
    restart: always
    networks:
      - travel_network

networks:
  travel_network:
    driver: bridge